partition:
  efi:
    full: /dev/nvme0n1p1
    dev: /dev/nvme0n1
    part: 1
  luks_container:
    path: /dev/sda2
    name: cryptlvm
    lvname:
      root: /dev/MyVol/root
      swap: /dev/MyVol/swap

system:
  locale: ja_JP.UTF-8
  keymap: jp106
  timezone: Asia/Tokyo

network:
  hostname: kimotu-vbox
  type: wired

username: kimotu

