partition:
  efi: /dev/sda1
  root:
    full: /dev/nvme0n1p2
    dev: /dev/nvme0n1
    part: 2

system:
  locale: ja_JP.UTF-8
  keymap: jp106
  timezone: Asia/Tokyo

network:
  hostname: kimotu-vbox
  type: wired

username: kimotu

