partition:
  efi:
    full: /dev/nvme0n1p1
    dev: /dev/nvme0n1
    part: 1
  root: /dev/sda2

system:
  locale: ja_JP.UTF-8
  keymap: jp106
  timezone: Asia/Tokyo

network:
  hostname: kimotu-vbox
  type: wired

username: kimotu

